# Generated by Django 5.1 on 2024-09-03 11:30

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заглавие')),
                ('slug', models.SlugField(max_length=255, verbose_name='слъг')),
                ('icon', models.CharField(choices=[('category_icon_1', 'Бебешки колички'), ('category_icon_2', 'Всичко за детето'), ('category_icon_3', 'Безопастност'), ('category_icon_4', 'Хигиена'), ('category_icon_5', 'Спорт'), ('category_icon_6', 'Уреди'), ('category_icon_7', 'За кола'), ('category_icon_8', 'За баня'), ('category_icon_9', 'Играчки'), ('category_icon_10', 'Хранене'), ('category_icon_11', 'Всичко за майката'), ('category_icon_12', 'Обзавеждане за стая'), ('category_icon_13', 'Облекло и аксесоари')], max_length=100, verbose_name='икона')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='под категория на')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
