# Generated by Django 5.1 on 2024-09-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='име')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
            ],
            options={
                'verbose_name': 'Производител',
                'verbose_name_plural': 'Производители',
            },
        ),
    ]
