# Generated by Django 5.1 on 2024-09-04 13:24

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='заглавие')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
            ],
            options={
                'verbose_name': 'Мерна единица',
                'verbose_name_plural': 'Мерни единици',
            },
        ),
        migrations.RemoveField(
            model_name='producer',
            name='name',
        ),
        migrations.AddField(
            model_name='producer',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='заглавие'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField(blank=True, default='', verbose_name='мета заглавие')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='мета описание')),
                ('meta_key_words', models.TextField(blank=True, default='', verbose_name='мета ключови думи')),
                ('title', models.CharField(default='', max_length=255, verbose_name='заглавие')),
                ('slug', models.SlugField(default='', max_length=255, verbose_name='слъг')),
                ('short_description', models.CharField(blank=True, default='', max_length=160, verbose_name='кратко описание')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='')),
                ('main_image', models.ImageField(upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='основна снимка')),
                ('youtube_link', models.URLField(blank=True, default='', verbose_name='ютюб линк')),
                ('nomenclature_number', models.CharField(default='', max_length=100, verbose_name='вътрешен номер')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='цена')),
                ('promotional_price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='промоционална цена')),
                ('available_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='налично количество')),
                ('weight_in_kilograms', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='тегло в килограми')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
                ('is_new', models.BooleanField(default=False, verbose_name='нов')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='категория')),
                ('freq_bought_together', models.ManyToManyField(blank=True, to='products.product', verbose_name='често купувани заедно')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.measureunit', verbose_name='мерна единица')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.producer', verbose_name='производител')),
                ('related_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='свързани продукти')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_files/', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xls', 'xlsx', 'pdf', 'txt', 'pptx'])], verbose_name='файл')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлове',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='снимка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Снимка',
                'verbose_name_plural': 'Снимки',
            },
        ),
    ]
