# Generated by Django 5.1 on 2024-09-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_measureunit_remove_producer_name_producer_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='промоционална цена'),
        ),
    ]
