# Generated by Django 5.1 on 2024-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_promotional_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='freq_bought_together',
            field=models.ManyToManyField(blank=True, related_name='freq_bought_together', to='products.product', verbose_name='често купувани заедно'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_products', to='products.product', verbose_name='свързани продукти'),
        ),
    ]
