# Generated by Django 5.1 on 2024-09-11 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('products', '0005_alter_product_freq_bought_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='freq_bought_together',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='често купувани заедно'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='свързани продукти'),
        ),
        migrations.DeleteModel(
            name='ProductFile',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
