# Generated by Django 5.1 on 2024-09-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productimage_product_remove_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='freq_bought_together',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='products.product', verbose_name='често купувани заедно'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.measureunit', verbose_name='мерна единица'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.producer', verbose_name='производител'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='products.product', verbose_name='свързани продукти'),
        ),
    ]
