# Generated by Django 5.1 on 2024-09-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_bg',
            field=models.SlugField(max_length=255, null=True, verbose_name='слъг'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='слъг'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='measureunit',
            name='title_bg',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='measureunit',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='producer',
            name='title_bg',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='producer',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_bg',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_key_words_bg',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета ключови думи'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_key_words_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета ключови думи'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_bg',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета заглавие'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета заглавие'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_bg',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='кратко описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='кратко описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_bg',
            field=models.SlugField(default='', max_length=255, null=True, verbose_name='слъг'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(default='', max_length=255, null=True, verbose_name='слъг'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_bg',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
    ]
