# Generated by Django 5.1 on 2024-09-13 10:59

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_baseuser_delete_individualuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='имена')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='имейл')),
                ('populated_place', models.CharField(blank=True, default='', max_length=255, verbose_name='населено място')),
                ('delivery_address', models.CharField(blank=True, default='', max_length=255, verbose_name='адрес за доставка')),
                ('phone_number', models.CharField(blank=True, default='', max_length=10, validators=[apps.common.validators.validate_phone], verbose_name='телефонен номер')),
                ('price_with_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='цена с ддс')),
                ('price_delivery', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='цена за доставка')),
                ('code', models.CharField(blank=True, default='', max_length=255, verbose_name='код')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='отстъпка')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата на създаване')),
                ('delivery_method', models.CharField(choices=[('to_office', 'до офис'), ('to_address', 'до адрес'), ('to_store_in_sofia', 'вземане от магазин в град София')], max_length=255, verbose_name='начин на доставка')),
                ('pay_method', models.CharField(choices=[('cash_on_delivery', 'наложен платеж'), ('with_card_on_courier', 'с карта на куриер')], max_length=255, verbose_name='начин на плащането')),
                ('pay_status', models.CharField(choices=[('expecting_cash_on_delivery_payment', 'очаква наложен платеж'), ('paid_with_cash_on_delivery', 'платено с наложен платеж'), ('expecting_bank_transfer', 'очаква банков превод'), ('paid_with_bank_transfer', 'платено с банков превод'), ('paid_with_dundio_card', 'платено с Dundio Club')], max_length=255, verbose_name='статус на плащането')),
                ('order_status', models.CharField(choices=[('new_order', 'нова поръчка'), ('unfinished_order', 'незавършена поръчка'), ('processed_order', 'обработена поръчка'), ('canceled_order', 'анулирана поръчка')], max_length=255, verbose_name='статус на поръчката')),
                ('is_invoice_wanted', models.BooleanField(default=False, verbose_name='желая фактура')),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.baseuser')),
            ],
            options={
                'verbose_name': 'Поръчка',
                'verbose_name_plural': 'Поръчки',
            },
        ),
    ]
