# Generated by Django 5.1 on 2024-09-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
        ('products', '0007_alter_product_category_and_more'),
        ('promotional_packages', '0002_remove_promotionalpackage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='поръчка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='products.product', verbose_name='продукт'),
        ),
        migrations.CreateModel(
            name='OrderPromotionalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_promotional_packages', to='orders.order', verbose_name='поръчка')),
                ('promotional_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_promotional_package', to='promotional_packages.promotionalpackage', verbose_name='промоционален пакет')),
            ],
            options={
                'verbose_name': 'Промоционален пакет',
                'verbose_name_plural': 'Промоционални пакети',
            },
        ),
    ]
