# Generated by Django 5.1 on 2024-09-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_bg',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='имена'),
        ),
        migrations.AddField(
            model_name='order',
            name='name_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='имена'),
        ),
        migrations.AddField(
            model_name='order',
            name='populated_place_bg',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='населено място'),
        ),
        migrations.AddField(
            model_name='order',
            name='populated_place_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='населено място'),
        ),
    ]
