# Generated by Django 5.1 on 2024-09-05 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_product_promotional_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='заглавие')),
            ],
            options={
                'verbose_name': 'Нов Акцент',
                'verbose_name_plural': 'Нови Акценти',
            },
        ),
        migrations.CreateModel(
            name='AccentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='заглавие')),
            ],
            options={
                'verbose_name': 'Промоционален Акцент',
                'verbose_name_plural': 'Промоционални Акценти',
            },
        ),
        migrations.CreateModel(
            name='AccentNewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accent_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accent_new_products', to='accents.accentnew', verbose_name='акцент нови')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accent_new_products', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Акцент нов продукт',
                'verbose_name_plural': 'Акцент нови продукти',
            },
        ),
        migrations.CreateModel(
            name='AccentPromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accent_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accent_promotion_products', to='accents.accentpromotion', verbose_name='акцент промоции')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accent_promotion_products', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Акцент промоционален продукт',
                'verbose_name_plural': 'Акцент промоционалени продукти',
            },
        ),
    ]
