# Generated by Django 5.1 on 2024-09-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accentnew',
            name='title_bg',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='accentnew',
            name='title_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='accentpromotion',
            name='title_bg',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='accentpromotion',
            name='title_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='заглавие'),
        ),
    ]
