# Generated by Django 5.1 on 2024-09-11 07:30

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='заглавие')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='адрес')),
                ('phone_number', models.CharField(blank=True, default='', max_length=10, validators=[apps.common.validators.validate_phone], verbose_name='телефонен номер')),
                ('work_time', models.CharField(blank=True, default='', max_length=255, verbose_name='работно време')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='отдел')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='', max_length=255, verbose_name='заглавие')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='имейл')),
                ('message_theme', models.CharField(default='', max_length=255, verbose_name='тема на съобщението')),
                ('phone_number', models.CharField(blank=True, default='', max_length=10, validators=[apps.common.validators.validate_phone], verbose_name='телефонен номер')),
                ('message', models.TextField(blank=True, default='', verbose_name='съобщение')),
            ],
            options={
                'verbose_name': 'Обратна връзка',
                'verbose_name_plural': 'Обратни връзки',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='заглавие')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='адрес')),
                ('phone_number', models.CharField(blank=True, default='', max_length=10, validators=[apps.common.validators.validate_phone], verbose_name='телефонен номер')),
                ('work_time', models.CharField(blank=True, default='', max_length=255, verbose_name='работно време')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='имейл')),
                ('lat', models.CharField(blank=True, default='', verbose_name='географска ширина')),
                ('lng', models.CharField(blank=True, default='', verbose_name='географска дължина')),
            ],
            options={
                'verbose_name': 'Обект',
                'verbose_name_plural': 'Обекти',
            },
        ),
    ]
