# Generated by Django 5.1 on 2024-09-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='department_bg',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='отдел'),
        ),
        migrations.AddField(
            model_name='contact',
            name='department_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='отдел'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_bg',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='object',
            name='title_bg',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='object',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
    ]
