# Generated by Django 5.1 on 2025-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_department_bg_contact_department_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="lat",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="географска ширина"
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="lng",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="географска дължина",
            ),
        ),
    ]
