# Generated by Django 5.1 on 2024-08-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='заглавие')),
                ('is_active', models.BooleanField(default=True, verbose_name='активност')),
            ],
            options={
                'verbose_name': 'Карусел банер',
                'verbose_name_plural': 'Карусел банери',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='заглавие')),
                ('image', models.ImageField(upload_to='carousel_images/', verbose_name='снимка')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('link', models.URLField(blank=True, default='', verbose_name='линк')),
                ('carousel_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='carousel_banner.carouselbanner')),
            ],
            options={
                'verbose_name': 'Карусел снимка',
                'verbose_name_plural': 'Карусел снимки',
            },
        ),
    ]
