# Generated by Django 5.1 on 2024-09-03 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_banner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='description',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='кратко описание'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(upload_to='carousel_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='снимка'),
        ),
    ]
