# Generated by Django 5.1 on 2024-09-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_banner', '0002_remove_carouselimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselbanner',
            name='title_bg',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='carouselbanner',
            name='title_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='short_description_bg',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='кратко описание'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='short_description_en',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='кратко описание'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title_bg',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='заглавие'),
        ),
    ]
