# Generated by Django 5.1 on 2024-09-11 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xls', 'xlsx', 'pdf', 'txt', 'pptx'])], verbose_name='файл')),
                ('base_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='common.basemodel', verbose_name='базов модел')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлове',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='снимка')),
                ('base_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='common.basemodel', verbose_name='базов модел')),
            ],
            options={
                'verbose_name': 'Снимка',
                'verbose_name_plural': 'Снимки',
            },
        ),
    ]
