# Generated by Django 5.1 on 2024-09-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedNewsletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='имейл')),
            ],
            options={
                'verbose_name': 'Имейл за бюлетин',
                'verbose_name_plural': 'Имейли за бюлетин',
            },
        ),
    ]
