# Generated by Django 5.1 on 2024-09-11 06:10

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('meta_title', models.TextField(blank=True, default='', verbose_name='мета заглавие')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='мета описание')),
                ('meta_key_words', models.TextField(blank=True, default='', verbose_name='мета ключови думи')),
                ('title', models.CharField(default='', max_length=255, verbose_name='заглавие')),
                ('slug', models.SlugField(default='', max_length=255, verbose_name='слъг')),
                ('short_description', models.CharField(blank=True, default='', max_length=160, verbose_name='кратко описание')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='')),
                ('main_image', models.ImageField(upload_to='text_page_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='основна снимка')),
                ('youtube_link', models.URLField(blank=True, default='', verbose_name='ютюб линк')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
            ],
            options={
                'verbose_name': 'Текстова страница',
                'verbose_name_plural': 'Текстови страници',
            },
            bases=('common.basemodel', models.Model),
        ),
    ]
