# Generated by Django 5.1 on 2024-09-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('information', 'информация'), ('customer_service', 'обслужване на клиенти'), ('additional_information', 'допълнителна информация'), ('my_profile', 'моят профил')], default='information', verbose_name='колона за подменюто')),
                ('title', models.CharField(default='', max_length=255, verbose_name='заглавие')),
                ('link', models.CharField(blank=True, default='', max_length=255, verbose_name='линк')),
            ],
            options={
                'verbose_name': 'Подменю',
                'verbose_name_plural': 'Подменюта',
            },
        ),
    ]
