# Generated by Django 5.1 on 2024-09-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0003_footermenu_title_bg_footermenu_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermenu',
            name='column',
            field=models.CharField(choices=[('information', 'Информация'), ('customer_service', 'Обслужване на клиенти'), ('additional_information', 'Допълнителна информация'), ('my_profile', 'Моят профил')], default='information', verbose_name='колона за подменюто'),
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Start with https:// or /', max_length=255, verbose_name='линк'),
        ),
    ]
