# Generated by Django 5.1 on 2025-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_pages", "0004_alter_footermenu_column_alter_footermenu_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footermenu",
            name="column",
            field=models.CharField(
                choices=[
                    ("information", "Информация"),
                    ("customer_service", "Обслужване на клиенти"),
                    ("additional_information", "Допълнителна информация"),
                    ("my_profile", "Моят профил"),
                ],
                default="information",
                max_length=255,
                verbose_name="колона за подменюто",
            ),
        ),
    ]
