# Generated by Django 5.1 on 2024-09-10 09:37

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, verbose_name='потребителско име')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='имейл')),
                ('full_name', models.CharField(blank=True, default='', max_length=100, verbose_name='имена')),
                ('phone_number', models.CharField(blank=True, default='', max_length=10, validators=[apps.common.validators.validate_phone], verbose_name='телефонен номер')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='адрес')),
                ('region', models.CharField(blank=True, default='', max_length=100, verbose_name='област')),
                ('populated_place', models.CharField(blank=True, default='', max_length=100, verbose_name='населено място')),
                ('postal_code', models.CharField(blank=True, default='', max_length=4, validators=[apps.common.validators.validate_postal_code], verbose_name='пощенски код')),
                ('delivery_address', models.CharField(blank=True, default='', max_length=100, verbose_name='адрес')),
                ('date_registered', models.DateField(auto_now_add=True, verbose_name='дата на регистрация')),
                ('dundio_club_card', models.CharField(blank=True, default='', max_length=100, verbose_name='дундио клуб карта')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='потвърденост')),
                ('dds', models.CharField(blank=True, default='', max_length=100, verbose_name='ддс')),
                ('mol', models.CharField(blank=True, default='', max_length=100, verbose_name='мол')),
                ('eik', models.CharField(blank=True, default='', max_length=100, verbose_name='еик')),
            ],
            options={
                'verbose_name': 'Юридическо лице',
                'verbose_name_plural': 'Юридически лица',
            },
        ),
        migrations.CreateModel(
            name='IndividualUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, verbose_name='потребителско име')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='имейл')),
                ('full_name', models.CharField(blank=True, default='', max_length=100, verbose_name='имена')),
                ('phone_number', models.CharField(blank=True, default='', max_length=10, validators=[apps.common.validators.validate_phone], verbose_name='телефонен номер')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='адрес')),
                ('region', models.CharField(blank=True, default='', max_length=100, verbose_name='област')),
                ('populated_place', models.CharField(blank=True, default='', max_length=100, verbose_name='населено място')),
                ('postal_code', models.CharField(blank=True, default='', max_length=4, validators=[apps.common.validators.validate_postal_code], verbose_name='пощенски код')),
                ('delivery_address', models.CharField(blank=True, default='', max_length=100, verbose_name='адрес')),
                ('date_registered', models.DateField(auto_now_add=True, verbose_name='дата на регистрация')),
                ('dundio_club_card', models.CharField(blank=True, default='', max_length=100, verbose_name='дундио клуб карта')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='потвърденост')),
            ],
            options={
                'verbose_name': 'Физическо лице',
                'verbose_name_plural': 'Физически лица',
            },
        ),
    ]
