# Generated by Django 5.1 on 2024-09-13 10:59

import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255, unique=True, verbose_name='потребителско име')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='имейл')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='имена')),
                ('phone_number', models.CharField(blank=True, default='', max_length=10, validators=[apps.common.validators.validate_phone], verbose_name='телефонен номер')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='адрес')),
                ('region', models.CharField(blank=True, default='', max_length=255, verbose_name='област')),
                ('populated_place', models.CharField(blank=True, default='', max_length=255, verbose_name='населено място')),
                ('postal_code', models.CharField(blank=True, default='', max_length=4, validators=[apps.common.validators.validate_postal_code], verbose_name='пощенски код')),
                ('delivery_address', models.CharField(blank=True, default='', max_length=255, verbose_name='адрес')),
                ('date_registered', models.DateField(auto_now_add=True, verbose_name='дата на регистрация')),
                ('dundio_club_card', models.CharField(blank=True, default='', max_length=255, verbose_name='дундио клуб карта')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='потвърденост')),
            ],
        ),
        migrations.DeleteModel(
            name='IndividualUser',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='dundio_club_card',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='populated_place',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='region',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='username',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='лице за контакт'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='dds',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ддс'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='eik',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='еик'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='mol',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='мол'),
        ),
        migrations.CreateModel(
            name='PhysicalUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseuser')),
            ],
            options={
                'verbose_name': 'Физическо лице',
                'verbose_name_plural': 'Физически лица',
            },
            bases=('users.baseuser',),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='baseuser_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseuser'),
            preserve_default=False,
        ),
    ]
