# Generated by Django 5.1 on 2024-09-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_delete_individualuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='address_bg',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='address_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='delivery_address_bg',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='delivery_address_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='full_name_bg',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='имена'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='full_name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='имена'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='populated_place_bg',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='населено място'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='populated_place_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='населено място'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='region_bg',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='област'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='region_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='област'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='contact_person_bg',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='лице за контакт'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='contact_person_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='лице за контакт'),
        ),
    ]
