# Generated by Django 5.1 on 2024-10-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_address_bg_baseuser_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='парола'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='имейл'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='потребителско име'),
        ),
        migrations.CreateModel(
            name='UserConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='токен')),
                ('is_used', models.BooleanField(default=False, verbose_name='използван')),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='users.baseuser', verbose_name='потребител')),
            ],
            options={
                'verbose_name': 'Потвърждаващ токен',
                'verbose_name_plural': 'Потвърждаващи токени',
            },
        ),
    ]
