# Generated by Django 5.1 on 2024-10-04 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_baseuser_password_alter_baseuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmationtoken',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата на създаване'),
        ),
    ]
