# Generated by Django 5.1 on 2025-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClubCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default="",
                        max_length=255,
                        unique=True,
                        verbose_name="номер на карта",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("accumulating_points", "натрупване на точки"),
                            ("vip", "вип"),
                        ],
                        default="accumulating_points",
                        max_length=255,
                        verbose_name="тип на карта",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="точки за карта натрупване на точки",
                    ),
                ),
                (
                    "fixed_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="фиксирана отстъпка за Вип карта",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="активност"),
                ),
            ],
            options={
                "verbose_name": "Карта Dundio Club",
                "verbose_name_plural": "Карти Dundio Club",
            },
        ),
    ]
