# Generated by Django 5.1 on 2024-09-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='брой')),
                ('discount_type', models.CharField(choices=[('percentage', 'процент'), ('fixed', 'фиксирана')], default='percentage', verbose_name='вид отстъпка')),
                ('discount_value', models.PositiveIntegerField(default=0, verbose_name='стойност на отстъпката')),
                ('valid_from_date', models.DateTimeField(blank=True, null=True, verbose_name='валидна от')),
                ('valid_to_date', models.DateTimeField(blank=True, null=True, verbose_name='валидна до')),
            ],
            options={
                'verbose_name': 'Генератор на код',
                'verbose_name_plural': 'Генератори на код',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True, verbose_name='заглавие')),
                ('discount_type', models.CharField(choices=[('percentage', 'процент'), ('fixed', 'фиксирана')], verbose_name='вид отстъпка')),
                ('discount_value', models.PositiveIntegerField(default=0, verbose_name='стойност на отстъпката')),
                ('valid_from_date', models.DateTimeField(blank=True, null=True, verbose_name='валидна от')),
                ('valid_to_date', models.DateTimeField(blank=True, null=True, verbose_name='валидна до')),
                ('status', models.CharField(choices=[('generated', 'генериран'), ('used', 'използван')], default='generated', verbose_name='статус')),
                ('generator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo_codes.promocodegenerator', verbose_name='генератор на код')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Кодове',
            },
        ),
    ]
