# Generated by Django 5.1 on 2025-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promo_codes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "процент"), ("fixed", "фиксирана")],
                max_length=255,
                verbose_name="вид отстъпка",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="status",
            field=models.CharField(
                choices=[("generated", "генериран"), ("used", "използван")],
                default="generated",
                max_length=255,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="promocodegenerator",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "процент"), ("fixed", "фиксирана")],
                default="percentage",
                max_length=255,
                verbose_name="вид отстъпка",
            ),
        ),
    ]
