# Generated by Django 5.1 on 2024-09-08 18:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_product_freq_bought_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField(blank=True, default='', verbose_name='мета заглавие')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='мета описание')),
                ('meta_key_words', models.TextField(blank=True, default='', verbose_name='мета ключови думи')),
                ('title', models.CharField(default='', max_length=255, verbose_name='заглавие')),
                ('slug', models.SlugField(default='', max_length=255, verbose_name='слъг')),
                ('main_image', models.ImageField(upload_to='promotional_package_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='основна снимка')),
                ('you_save', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='вие спестявате')),
                ('youtube_link', models.URLField(blank=True, default='', verbose_name='ютюб линк')),
                ('valid_from_date', models.DateField(verbose_name='валиден от')),
                ('valid_to_date', models.DateField(blank=True, null=True, verbose_name='валиден до')),
                ('is_active', models.BooleanField(default=False, verbose_name='активност')),
                ('is_new', models.BooleanField(default=False, verbose_name='нов')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotional_packages', to='products.category', verbose_name='категория')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotional_packages', to='products.measureunit', verbose_name='мерна единица')),
                ('products', models.ManyToManyField(blank=True, related_name='promotional_packages', to='products.product', verbose_name='продукти')),
                ('related_packages', models.ManyToManyField(blank=True, related_name='related_packages', to='promotional_packages.promotionalpackage', verbose_name='свързани пакети')),
            ],
            options={
                'verbose_name': 'Промоционален пакет',
                'verbose_name_plural': 'Промоционални пакети',
            },
        ),
        migrations.CreateModel(
            name='PromotionalPackageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='заглавие')),
                ('file', models.FileField(upload_to='promotional_package_files/', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xls', 'xlsx', 'pdf', 'txt', 'pptx'])], verbose_name='файл')),
                ('promotional_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='promotional_packages.promotionalpackage', verbose_name='промоционален пакет')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлове',
            },
        ),
    ]
