# Generated by Django 5.1 on 2024-09-11 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('promotional_packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionalpackage',
            name='id',
        ),
        migrations.AddField(
            model_name='promotionalpackage',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotionalpackage',
            name='related_packages',
            field=models.ManyToManyField(blank=True, to='promotional_packages.promotionalpackage', verbose_name='свързани пакети'),
        ),
        migrations.DeleteModel(
            name='PromotionalPackageFile',
        ),
    ]
