# Generated by Django 5.1 on 2024-09-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotional_packages', '0002_remove_promotionalpackage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalpackage',
            name='meta_description_bg',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета описание'),
        ),
        migrations.AddField(
            model_name='promotionalpackage',
            name='meta_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета описание'),
        ),
        migrations.AddField(
            model_name='promotionalpackage',
            name='meta_key_words_bg',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета ключови думи'),
        ),
        migrations.AddField(
            model_name='promotionalpackage',
            name='meta_key_words_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета ключови думи'),
        ),
        migrations.AddField(
            model_name='promotionalpackage',
            name='meta_title_bg',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета заглавие'),
        ),
        migrations.AddField(
            model_name='promotionalpackage',
            name='meta_title_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='мета заглавие'),
        ),
        migrations.AddField(
            model_name='promotionalpackage',
            name='slug_bg',
            field=models.SlugField(default='', max_length=255, null=True, verbose_name='слъг'),
        ),
        migrations.AddField(
            model_name='promotionalpackage',
            name='slug_en',
            field=models.SlugField(default='', max_length=255, null=True, verbose_name='слъг'),
        ),
        migrations.AddField(
            model_name='promotionalpackage',
            name='title_bg',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
        migrations.AddField(
            model_name='promotionalpackage',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='заглавие'),
        ),
    ]
